### ISSUE TITLE
találtam neked 1 typo-t :D

### ISSUE THREAD

**Issue by szbnwer** [artit91/rustberry_pi#1]
https://github.com/artit91/rustberry_pi/blob/8e944eb6fa2b2c99ab333624a529341429b5f4b9/src/sys/alloc/mod.rs#L35

(amúgy már még némiképp meg is teccett a rust így olvasgatás közben, egész emészthető, bár az oop-t még mindig nem tudtam megszeretni... :D másrészt aszittem valami fejlettebb cuccot hájpoltál be saját kernel néven, még ha látom is hogy friss, meg attól még az is valami, harmadrészt pedig bocsi hogy idetresselek! X'D )

**Comment by artit91** [comment]
fixed :D

👯‍♂️
